<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('cars')->delete();

        DB::table('cars')->insert(array (
            0 =>
            array (
                'id' => 1,
                'deleted_at' => NULL,
                'chassi' => '11111',
                'category' => 'Economy',
                'models_id' => 8,
                'color_id' => 4,
                'brand_id' => 1,
                'fuel_id' => 1,
                'manufacture_date' => 2016,
                'supplier_id' => 1,
                'mileage' => 40,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'engine' => '60',
                'transmission' => 'Manual',
                'registration_date' => '2025-09-08',
                'observations' => 'Um carro ótimo para o dia-à-dia.',
                'license_plate' => 'LD-01-01-KL',
                'image' => '1757334779_image.jfif',
                'car_insurance' => '11111',
                'car_insurance_upload' => '1757334779_insurance.pdf',
                'car_document' => '11111',
                'car_document_upload' => '1757334779_document.pdf',
                'inspection_date' => '2025-06-04',
                'inspection_document_upload' => '1757334779_inspection.pdf',
                'price' => '32000.00',
                'created_at' => '2025-09-08 12:32:59',
                'updated_at' => '2025-09-08 12:52:54',
                'status' => 'available',
            ),
            1 =>
            array (
                'id' => 2,
                'deleted_at' => NULL,
                'chassi' => '22222',
                'category' => 'Economy',
                'models_id' => 2,
                'color_id' => 2,
                'brand_id' => 2,
                'fuel_id' => 4,
                'manufacture_date' => 2017,
                'supplier_id' => 1,
                'mileage' => 80,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'engine' => '65',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-08',
                'observations' => 'Prático para dias corridos.',
                'license_plate' => 'LD-02-02-HD',
                'image' => '1757334946_image.jfif',
                'car_insurance' => '22222',
                'car_insurance_upload' => '1757334946_insurance.pdf',
                'car_document' => '22222',
                'car_document_upload' => '1757334946_document.pdf',
                'inspection_date' => '2025-01-16',
                'inspection_document_upload' => '1757334946_inspection.pdf',
                'price' => '30000.00',
                'created_at' => '2025-09-08 12:35:46',
                'updated_at' => '2025-09-08 13:01:01',
                'status' => 'reserved',
            ),
            2 =>
            array (
                'id' => 3,
                'deleted_at' => NULL,
                'chassi' => '33333',
                'category' => 'Economy',
                'models_id' => 4,
                'color_id' => 3,
                'brand_id' => 4,
                'fuel_id' => 1,
                'manufacture_date' => 2019,
                'supplier_id' => 1,
                'mileage' => 70,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'engine' => '75',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-09',
                'observations' => 'O carro ideal para serviços privados.',
                'license_plate' => 'LD-03-03-HD',
                'image' => '1757420207_image.jfif',
                'car_insurance' => '33333',
                'car_insurance_upload' => '1757420207_insurance.pdf',
                'car_document' => '33333',
                'car_document_upload' => '1757420207_document.pdf',
                'inspection_date' => '2025-09-09',
                'inspection_document_upload' => '1757420207_inspection.pdf',
                'price' => '40000.00',
                'created_at' => '2025-09-09 12:16:47',
                'updated_at' => '2025-09-09 12:16:47',
                'status' => 'available',
            ),
            3 =>
            array (
                'id' => 4,
                'deleted_at' => NULL,
                'chassi' => '44444',
                'category' => 'Economy',
                'models_id' => 3,
                'color_id' => 2,
                'brand_id' => 4,
                'fuel_id' => 4,
                'manufacture_date' => 2017,
                'supplier_id' => 1,
                'mileage' => 50,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'engine' => '76',
                'transmission' => 'Manual',
                'registration_date' => '2025-09-09',
                'observations' => 'Carro simples e muito económico.',
                'license_plate' => 'LD-04-04-HD',
                'image' => '1757420476_image.jfif',
                'car_insurance' => '44444',
                'car_insurance_upload' => '1757420476_insurance.pdf',
                'car_document' => '44444',
                'car_document_upload' => '1757420476_document.pdf',
                'inspection_date' => '2025-09-09',
                'inspection_document_upload' => '1757420476_inspection.pdf',
                'price' => '35000.00',
                'created_at' => '2025-09-09 12:21:16',
                'updated_at' => '2025-09-09 21:15:29',
                'status' => 'reserved',
            ),
            4 =>
            array (
                'id' => 5,
                'deleted_at' => NULL,
                'chassi' => '55555',
                'category' => 'Standard',
                'models_id' => 5,
                'color_id' => 4,
                'brand_id' => 2,
                'fuel_id' => 1,
                'manufacture_date' => 2018,
                'supplier_id' => 2,
                'mileage' => 0,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'engine' => '78',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-09',
                'observations' => 'Garante mais segurança e possui maior conforto!',
                'license_plate' => 'LD-05-05-HD',
                'image' => '1757420664_image.jfif',
                'car_insurance' => '55555',
                'car_insurance_upload' => '1757420664_insurance.pdf',
                'car_document' => '55555',
                'car_document_upload' => '1757420664_document.pdf',
                'inspection_date' => '2025-09-09',
                'inspection_document_upload' => '1757420664_inspection.pdf',
                'price' => '50000.00',
                'created_at' => '2025-09-09 12:24:24',
                'updated_at' => '2025-09-09 12:24:24',
                'status' => 'available',
            ),
            5 =>
            array (
                'id' => 6,
                'deleted_at' => NULL,
                'chassi' => '66666',
                'category' => 'Standard',
                'models_id' => 6,
                'color_id' => 2,
                'brand_id' => 3,
                'fuel_id' => 4,
                'manufacture_date' => 2019,
                'supplier_id' => 2,
                'mileage' => 80,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'engine' => '75',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-09',
                'observations' => 'Carro potente e sofisticado.',
                'license_plate' => 'LD-06-06-HD',
                'image' => '1757421754_image.jfif',
                'car_insurance' => '66666',
                'car_insurance_upload' => '1757421754_insurance.pdf',
                'car_document' => '66666',
                'car_document_upload' => '1757421754_document.pdf',
                'inspection_date' => '2025-09-09',
                'inspection_document_upload' => '1757421754_inspection.pdf',
                'price' => '55000.00',
                'created_at' => '2025-09-09 12:42:34',
                'updated_at' => '2025-09-09 12:42:34',
                'status' => 'available',
            ),
        ));


    }
}
